# -*- coding: utf-8 -*-
# SPDX-License-Identifier: Apache-2.0
# GeoPrior-v3 — https://github.com/earthai-tech/geoprior-v3
# Copyright (c) 2026-present
# Author: LKouadio <https://lkouadio.com>

"""
Central configuration for backend-specific object mappings.

This module acts as the single source of truth for locating objects
within different backends like TensorFlow/Keras. It allows for a
clean separation of configuration from the logic in the dependency
loaders.
"""

_STANDARD_ALONE_MAP = {
    'AUTOTUNE': ('tensorflow.data', 'AUTOTUNE'),
    'Assert': ('tensorflow', 'Assert'),
    'Dataset': ('tensorflow.data', 'Dataset'),
    'GradientTape': ('tensorflow', 'GradientTape'),
    'IndexedSlices': ('tensorflow', 'IndexedSlices'), 
    'Tensor': ('tensorflow', 'Tensor'),
    'TensorShape': ('tensorflow', 'TensorShape'),
    'Variable': ('tensorflow', 'Variable'),
    
    'abs': ('tensorflow', 'abs'),
    'activations': ('tensorflow.keras', 'activations'),
    'add': ('tensorflow.math', 'add'),
    'add_n': ('tensorflow.math', 'add_n'),
    'argmin': ('tensorflow', 'argmin'), 
    'assert_equal': ('tensorflow', 'assert_equal'),
    'autograph': ('tensorflow', 'autograph'),
    'backend': ('tensorflow.keras', 'backend'),
    'broadcast_to': ('tensorflow', 'broadcast_to'), 
    'bool': ('tensorflow', 'bool'),
    'cast': ('tensorflow', 'cast'),
    'clip_by_value':('tensorflow', 'clip_by_value'), 
    'clip_by_global_norm': ('tensorflow', 'clip_by_global_norm'), 
    'concat': ('tensorflow', 'concat'),
    'cond': ('tensorflow', 'cond'),
    'constant': ('tensorflow', 'constant'),
    'control_dependencies': ('tensorflow', 'control_dependencies'),
    'convert_to_tensor': ('tensorflow', 'convert_to_tensor'),
    'cos': ('tensorflow', 'cos'),
    'cumsum': ('tensorflow.math', 'cumsum'), 
    'debugging': ('tensorflow', 'debugging'),
    'divide_no_nan': ('tensorflow.math', 'divide_no_nan'), 
    'errors': ('tensorflow', 'errors'),
    'equal': ('tensorflow', 'equal'),
    'erf': ('tensorflow.math', 'erf'), 
    'executing_eagerly': ('tensorflow', 'executing_eagerly'), 
    'exp': ('tensorflow', 'exp'),
    'expand_dims': ('tensorflow', 'expand_dims'),
    'experimental':('tensorflow.data', 'experimental'), 
    'fill': ('tensorflow', 'fill'),
    'float32': ('tensorflow', 'float32'),
    'float64': ('tensorflow', 'float64'),
    'floordiv': ('tensorflow.math', 'floordiv'),
    'gather': ('tensorflow', 'gather'),
    'get_static_value': ('tensorflow', 'get_static_value'),
    'greater': ('tensorflow', 'greater'),
    'greater_equal': ('tensorflow', 'greater_equal'),
    'identity': ('tensorflow', 'identity'),
    'int32': ('tensorflow', 'int32'),
    'int64': ('tensorflow', 'int64'),
    'is_inf': ('tensorflow.math', 'is_inf'),    
    'is_nan': ('tensorflow.math', 'is_nan'),
    'less': ('tensorflow', 'less'),
    'less_equal': ('tensorflow', 'less_equal'),
    'linalg': ('tensorflow', 'linalg'),
    'log': ('tensorflow.math', 'log'),
    'logical_and': ('tensorflow', 'logical_and'),
    'logical_not': ('tensorflow', 'logical_not'),
    'logical_or': ('tensorflow', 'logical_or'),
    'math': ('tensorflow', 'math'), 
    'maximum': ('tensorflow.math', 'maximum'),
    'minimum': ('tensorflow.math', 'minimum'),
    'multiply': ('tensorflow', 'multiply'),
    'name_scope': ('tensorflow', 'name_scope'),
    'nest': ('tensorflow', 'nest'), 
    'newaxis': ('tensorflow', 'newaxis'),
    'no_op': ('tensorflow', 'no_op'),
    'nn': ('tensorflow', 'nn'), 
    'ones': ('tensorflow', 'ones'), 
    'ones_like':('tensorflow', 'ones_like'), 
    'pad': ('tensorflow', 'pad'),
    'pow': ('tensorflow', 'pow'),
    'print': ('tensorflow', 'print'),
    'random': ('tensorflow', 'random'),
    'range': ('tensorflow', 'range'),
    'rank': ('tensorflow', 'rank'),
    'reduce_any':('tensorflow', 'reduce_any'), 
    'reduce_all': ('tensorflow', 'reduce_all'),
    'reduce_logsumexp':('tensorflow.math', 'reduce_logsumexp'), 
    'reduce_max': ('tensorflow', 'reduce_max'),
    'reduce_mean': ('tensorflow', 'reduce_mean'),
    'reduce_min': ('tensorflow', 'reduce_min'),
    'reduce_sum': ('tensorflow', 'reduce_sum'),
    'regularizers': ('tensorflow.keras', 'regularizers'),
    'repeat': ('tensorflow', 'repeat'),
    'reshape': ('tensorflow', 'reshape'),
    'sequence_mask': ('tensorflow', 'sequence_mask'), 
    'set_seed': ('tensorflow.random', 'set_seed'),
    'scan': ('tensorflow', 'scan'), 
    'shape': ('tensorflow', 'shape'),
    'sigmoid': ('tensorflow.math', 'sigmoid'), 
    'sin': ('tensorflow', 'sin'),
    'size': ('tensorflow', 'size'),
    'softplus': ('tensorflow.math', 'softplus'), 
    'sort': ('tensorflow', 'sort'), 
    'string': ('tensorflow', 'string'), 
    'stop_gradient': ('tensorflow','stop_gradient' ), 
    'split': ('tensorflow', 'split'),
    'squeeze': ('tensorflow', 'squeeze'),
    'square': ('tensorflow.math', 'square'),
    'sqrt': ('tensorflow', 'sqrt'), 
    'stack': ('tensorflow', 'stack'),
    'subtract': ('tensorflow', 'subtract'),
    'switch_case': ('tensorflow', 'switch_case'), 
    'tile': ('tensorflow', 'tile'),
    'transpose': ('tensorflow', 'transpose'),
    'unstack': ('tensorflow', 'unstack'),
    'where': ('tensorflow', 'where'),
    'zeros': ('tensorflow', 'zeros'),
    'zeros_like': ('tensorflow', 'zeros_like'),
}

TENSORFLOW_CONFIG = {
    **_STANDARD_ALONE_MAP,
    'Activation': ('layers', 'Activation'),
    'Adam': ('optimizers', 'Adam'),
    'Add': ('layers', 'Add'),
    'Attention': ('layers', 'Attention'),
    'BatchNormalization': ('layers', 'BatchNormalization'),
    'Bidirectional': ('layers', 'Bidirectional'),
    'Callback': ('callbacks', 'Callback'),
    'Concatenate': ('layers', 'Concatenate'),
    'Constant': ('initializers', 'Constant'),
    'Constraint': ('constraints', 'Constraint'), 
    'Conv1D': ('layers', 'Conv1D'),
    'Conv2D': ('layers', 'Conv2D'),
    'Dense': ('layers', 'Dense'),
    'Dropout': ('layers', 'Dropout'),
    'ELU': ('layers', 'ELU'),
    'EarlyStopping': ('callbacks', 'EarlyStopping'),
    'Embedding': ('layers', 'Embedding'),
    'Flatten': ('layers', 'Flatten'),
    'GlobalAveragePooling1D': ('layers', 'GlobalAveragePooling1D'),
    'GlobalAveragePooling2D': ('layers', 'GlobalAveragePooling2D'),
    'History': ('callbacks', 'History'),
    'Input': ('layers', 'Input'),
    'InputLayer': ('layers', 'InputLayer'),
    'K': ('backend', 'K'),
    'LSTM': ('layers', 'LSTM'),
    'LSTMCell': ('layers', 'LSTMCell'),
    'Layer': ('layers', 'Layer'),
    'LayerNormalization': ('layers', 'LayerNormalization'),
    'LearningRateScheduler': ('callbacks', 'LearningRateScheduler'),
    'Loss': ('losses', 'Loss'),
    'MaxPooling1D': ('layers', 'MaxPooling1D'),
    'MaxPooling2D': ('layers', 'MaxPooling2D'),
    'Mean': ('metrics', 'Mean'),
    'MeanAbsoluteError': ('metrics', 'MeanAbsoluteError'),
    'MeanSquaredError': ('losses', 'MeanSquaredError'),
    'Metric': ('metrics', 'Metric'),
    'Model': ('models', 'Model'),
    'ModelCheckpoint': ('callbacks', 'ModelCheckpoint'),
    'MultiHeadAttention': ('layers', 'MultiHeadAttention'),
    'Optimizer': ('optimizers', 'Optimizer'),
    'RMSprop': ('optimizers', 'RMSprop'),
    'RandomNormal': ('initializers', 'RandomNormal'), 
    'Reduction': ('losses','Reduction' ), 
    'ReduceLROnPlateau': ('callbacks', 'ReduceLROnPlateau'),
    'RepeatVector': ('layers', 'RepeatVector'),
    'SGD': ('optimizers', 'SGD'),
    'Sequential': ('models', 'Sequential'),
    'Softmax': ('layers', 'Softmax'),
    'TensorBoard': ('callbacks', 'TensorBoard'),
    'TimeDistributed': ('layers', 'TimeDistributed'),
    
    'binary_crossentropy': ('losses', 'binary_crossentropy'),
    'categorical_crossentropy': ('losses', 'categorical_crossentropy'),
    'cifar10': ('datasets', 'cifar10'),
    'clone_model': ('models', 'clone_model'),
    'custom_object_scope': ('utils', 'custom_object_scope'), 
    'deserialize_keras_object': (
        ('saving', 'deserialize_keras_object'), 
        ('utils', 'deserialize_keras_object')
    ),
    'get': ('losses', 'get'), 
    'glorot_uniform': ('initializers', 'glorot_uniform'),
    'load_model': ('models', 'load_model'),
    'mean_squared_error': ('losses', 'mean_squared_error'),
    'mnist': ('datasets', 'mnist'),
    'ones': ('backend', 'ones'),
    'random_normal': ('initializers', 'random_normal'),
    'register_keras_serializable': (
        ('saving', 'register_keras_serializable'), 
        ('utils', 'register_keras_serializable')
    ),
    'serialize_keras_object': (
        ('saving', 'serialize_keras_object'), 
        # ('utils', 'serialize_keras_object')
    ),
    'sum': ('backend', 'sum'),
    
}
# Configuration for KerasTuner
KERAS_TUNER_CONFIG = {
    'BayesianOptimization': ('keras_tuner', 'BayesianOptimization'),
    'Hyperband': ('keras_tuner', 'Hyperband'), 
    'HyperModel': ('keras_tuner', 'HyperModel'),
    'HyperParameters': ('keras_tuner', 'HyperParameters'),
    'Objective': ('keras_tuner', 'Objective'),
    'RandomSearch': ('keras_tuner', 'RandomSearch'),
    'Tuner': ('keras_tuner', 'Tuner'),
    'TunerCallback': (
        ('keras_tuner.src.engine.tuner_utils', 'TunerCallback'), 
        ('keras_tuner.engine.tuner_utils', 'TunerCallback')
    ),
}

